DROP TABLE IF EXISTS users, items, comments, bookings;

CREATE TABLE IF NOT EXISTS Users (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT pk_user PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS Comments (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    text VARCHAR NOT NULL,
    author_name VARCHAR NOT NULL,
    created TIMESTAMP NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
    );
CREATE TABLE IF NOT EXISTS Items (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    available BOOLEAN NOT NULL,
    owner_id BIGINT NOT NULL,
    comment_id BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_item_owner_id FOREIGN KEY (owner_id) REFERENCES Users(id),
    CONSTRAINT fk_comment_id FOREIGN KEY (comment_id) REFERENCES Comments(id)
);

CREATE TABLE IF NOT EXISTS ITEMS_COMMENTS (
    item_id BIGINT NOT NULL,
    comments_id BIGINT NOT NULL,
    PRIMARY KEY (item_id, comments_id),
    CONSTRAINT fk_item FOREIGN KEY (item_id) REFERENCES Items(id),
    CONSTRAINT fk_comment FOREIGN KEY (comments_id) REFERENCES Comments(id)
);


CREATE TABLE IF NOT EXISTS Bookings (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    booker_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_booker_id FOREIGN KEY (booker_id) REFERENCES Users(id),
    CONSTRAINT fk_item_id FOREIGN KEY (item_id) REFERENCES Items(id)
)